### ISSUE TITLE
blank data csv file download

### ISSUE THREAD

**Issue by krunalp1993** [react-csv/react-csv#111]
In my react web app i am assign dynamic data variable to csvlink but when i am press on it. it will download  only headers no data is there please fix this problem..

**Comment by mccabemj** [comment]
Can you give us an example of the dynamic data you are using? Are you using the headers prop? If so, please provide that headers object

**Comment by krunalp1993** [comment]
> Can you give us an example of the dynamic data you are using? Are you using the headers prop? If so, please provide that headers object

const headers =
  [
    { label: 'Meterno', key: 'meterNo' },
    { label: 'Voucher', key: 'esipayVoucher' },
    { label: 'Amount', key: 'amount' },
    { label: 'Units', key: 'units' },
    { label: 'Type', key: 'type' },
    { label: 'Reference', key: 'reference' },
    { label: 'Created Date', key: 'createdAt' },
  ];

**Comment by mccabemj** [comment]
Ok great. And the data?

**Comment by krunalp1993** [comment]
![screenshot from 2018-10-23 12-49-40](https://user-images.githubusercontent.com/5568019/47343392-95809980-d6c3-11e8-81d7-a893e598ffa4.png)

**Comment by mccabemj** [comment]
From quick glance I can see that you are referencing a key “meterNo” but there is no key in your data with that (presume you mean “meter”). 
Also, esipayVoucher is an array so would not output. I am surprised your getting no data at all. Try omitting those two keys from your headers and see if the data exports

**Comment by krunalp1993** [comment]
> From quick glance I can see that you are referencing a key “meterNo” but there is no key in your data with that (presume you mean “meter”).
> Also, esipayVoucher is an array so would not output. I am surprised your getting no data at all. Try omitting those two keys from your headers and see if the data exports

i am omitting those two keys but problem still exist...

**Comment by Vieshanis** [comment]
+1

**Comment by mccabemj** [comment]
@krunalp1993 are you sure the data has downloaded into state before the button is rendered? You should only render the button once you have the data. Your saying its dynamic data, so this may be it. Your headers are static so they are shown, but your data is not.

if you simply have something like this on the page, if the data is not there waiting when the page renders, it would output a blank file
```
<CSVLink data={this.state.data} headers={headers}>Download</CSVLink>
```

If you are waiting for asynchronous dynamic data, you'll need to do something like

```
{ this.state.data ? <CSVLink data={this.state.data} headers={headers}>Download</CSVLink> : null }
```

**Comment by mriccid** [comment]
@mccabemj I think that the changes from https://github.com/react-csv/react-csv/pull/88 are problematic in the way that they require the component to be mounted once the CSV data is in state in order for the `href` state to be correctly computed. This seems like an unnecessary amount of complexity to me. With the rule of least surprise in mind, it also feels like the behaviour is confusing. 

I think that the state should be updated every time the component receives new props. That would most likely solve the problem that @krunalp1993 is having.

**Comment by mccabemj** [comment]
@mriccid very valid point. I didn't see the issue with that PR at the time. I think we may need to consider this being a browser only package, and creating a separate ones for server side/react-native/desktop versions.

I'd be in favour of reverting that PR. @abdennour your thoughts?

**Comment by mriccid** [comment]
I’d be happy to modify it so that it is also re-computed when the props change, rather than just when the component is mounted. That would satisfy the problem in this issue while still supporting

**Comment by krunalp1993** [comment]
> @krunalp1993 are you sure the data has downloaded into state before the button is rendered? You should only render the button once you have the data. Your saying its dynamic data, so this may be it. Your headers are static so they are shown, but your data is not.
> 
> if you simply have something like this on the page, if the data is not there waiting when the page renders, it would output a blank file
> 
> ```
> <CSVLink data={this.state.data} headers={headers}>Download</CSVLink>
> ```
> If you are waiting for asynchronous dynamic data, you'll need to do something like
> 
> ```
> { this.state.data ? <CSVLink data={this.state.data} headers={headers}>Download</CSVLink> : null }
> ```

Hey author thanks for this solution now this is working fine thanks a lot and sorry for late replay..

**Comment by ifeanyidavid** [comment]
> @krunalp1993 are you sure the data has downloaded into state before the button is rendered? You should only render the button once you have the data. Your saying its dynamic data, so this may be it. Your headers are static so they are shown, but your data is not.
> 
> if you simply have something like this on the page, if the data is not there waiting when the page renders, it would output a blank file
> 
> ```
> <CSVLink data={this.state.data} headers={headers}>Download</CSVLink>
> ```
> If you are waiting for asynchronous dynamic data, you'll need to do something like
> 
> ```
> { this.state.data ? <CSVLink data={this.state.data} headers={headers}>Download</CSVLink> : null }
> ```

I more guaranteed of making doing this is:
```{this.state.data.length ? <CSVLink data={this.state.data} headers={headers}>Download</CSVLink> : null }```
Using just `this.state.data` doesn't guaranteed that it the data will get loaded in the CSV file because if you declare data as an empty array in the state, it will render the button regardless of whether the data has arrived.

**Comment by gschwendt** [comment]
Just to add to the conversation, this seems to also happen if you have a functional component that is setting the data variable. 

For example, I was passing down a state variable (timesheets) to my fuctional component as a prop and the component was supposed to set the csvHeaders and csvData variables based upon props.timesheets. 

Even when I did the following, it still generated an empty CSV file (aside from the headers), likely because the initial state for timesheets was an empty array:
```
let csvData = []; 
props.timesheets.forEach(timesheet => {
    csvData.push(timesheet);
}); 

return (
    <div>
       { csvData.length > 0 ? <
            <CSVLink data={csvData} headers={csvHeaders} target='_blank'>Download CSV</CSVLink> 
             : null }
    </div>
);
```

I fixed this by building the csvData as a state variable in my parent class component and passing the csvData as a prop to my child functional component.

**Comment by manayko-lineate** [comment]
If you have an empty csv file in IE and getting csv data from state, you might need to use 

```
handleCsvExport() {
   ...

    this.setState({
      ...this.state,
      csvData
    });
  }

...

<CSVLink
   data={this.state.csvData}
   onClick={(event, done) => {
      this.handleCsvExport();
      done();
   }}
   asyncOnClick={true}
   filename={`${config.widgetId}.csv`}
>
   Export data
</CSVLink>
```
