### ISSUE TITLE
No update when data prop changes

### ISSUE THREAD

**Issue by hijackthegit** [react-csv/react-csv#115]
My use case is the container will fire some API based on user's input, and the csv data could be changed overtime, but when pass props with new csv data into CSVLink component, the state will get never changed. 
I looked into the source: 
node_modules/react-csv/src/components/Link.js the state change only happen in componentDidMount. Seems the href only be generated once when the component mounts.

Wondering if "this.setState()" should also apply to componentWillUpdate() in order to apply new data passed via props. I might wrong about this or the implementation should be in another way around?

Thanks

**Comment by mriccid** [comment]
You are correct that the state should be updated when the props change. This behaviour was broken in a PR recently and will be fixed very soon.

**Comment by mccabemj** [comment]
Linking #111 for reference. @mriccid are you working on a fix?

**Comment by hijackthegit** [comment]
Thanks for quick response. Looking fwd to the fix. My current work around is:
`class PropDataUpdatedCSVLink extends CSVLink {
	constructor(props) {
		super(props);
	}

	componentWillReceiveProps(nextProps) {
		const { data, headers, separator, uFEFF } = nextProps;
		this.setState({ href: this.buildURI(data, uFEFF, headers, separator) });
	}
}`

and use PropDataUpdatedCSVLink instead of CSVLink.

**Comment by ttrzeng** [comment]
Can someone fork this and update this to the repo? I'm currently using this for production.

**Comment by mzohaibqc** [comment]
One simple situation in such scenarios is to update key which will trigger re-render

**Comment by mccabemj** [comment]
@hijackthegit thanks for finding the original issue and providing help with the fix. Thanks to @ttrzeng for doing the PR. Its now been merged and released under version 1.0.19

**Comment by isuruamantha** [comment]
Many thanks for the release. Saved my life :+1:

**Comment by moa-novae** [comment]
I am experiencing the same problem in v2.0.1 Not sure if anyone else is too. Adding a key to the component as @mzohaibqc suggested solves the issue.

**Comment by 91juhwang** [comment]
> 

Same!
