### ISSUE TITLE
'from: ' metadata is not showing the origin

### ISSUE THREAD

**Issue by davegomez** [react-csv/react-csv#119]
When trying to download the file using a browser like **Firefox**, the from metadata in the download window don't display the origin correctly, instead display the word **blob:**.

I think is should be the URL.

![blob](https://user-images.githubusercontent.com/282903/48506422-67502e80-e817-11e8-885a-8ca1b7a6f271.png)

**Comment by mriccid** [comment]
Which URL are you expecting to see? The above message is correct in the sense that the Blob URL is what is being downloaded.

**Comment by davegomez** [comment]
Your are right. I was expecting to see the host URL but just remember this file is being generated on the client using Blob.

Closing this issue.
