### ISSUE TITLE
It doesn't work with Safari

### ISSUE THREAD

**Issue by TongMonkey** [react-csv/react-csv#123]

**Comment by mccabemj** [comment]
@TongMonkey can you give us some more context as to the issue your having? What’s your data and the source of it? Are you using the link or the download?

**Comment by mashehu** [comment]
Hi,

I am also having problems with the CSVLink component and Safari. I can reproduce the error with the sample page. In Safari 12.0 when I click on the "export to CSV" button, a new tab opens with the following error message `Safari can’t open the page “blob:http://localhost:8008/401a32ef-8596-4fe1-942c-efed2c5ac21e”.
The error is: “The operation couldn’t be completed. (WebKitBlobResource error 1.)” (WebKitBlobResource:1))`
No error messages in the console. Any more ways how I can help debugging this?

**Comment by jmtucker7** [comment]
I am getting this same error with Safari.  Chrome works as expected.  I am getting nothing in Firefox.  Any ideas?

**Comment by mretzak** [comment]
I ran into this as well, but was able to get around it by adding a `target="_self"` attribute to the `<CSVLink />` tag.
