### ISSUE TITLE
sort / filter to csv file

### ISSUE THREAD

**Issue by xwilluhn** [react-csv/react-csv#124]
<CSVLink data={props.data}>
when the props.data change, after filtering, sorting, the resulting csv file uses the same data, the initial data, not sorted, not filtered.
I use react-redux, no react router management. I wonder if it is something to do with router change.
Any idea?

**Comment by xwilluhn** [comment]
"react-csv": "1.0.18",

**Comment by mccabemj** [comment]
@xwilluhn this was fixed in 1.0.19

**Comment by xwilluhn** [comment]
thanks! let me try 1.0.19 and let you know

**Comment by xwilluhn** [comment]
yes, it works. Thank a lot. @mccabemj
