### ISSUE TITLE
Exporting invalid data for Numbers in CSV

### ISSUE THREAD

**Issue by ksgr** [react-csv/react-csv#126]
Numerics are not handled properly, generating invalid data if its more then 15 digit number
ex : 123456789123456789 -> 
           should output ->  123456789123456789
           actual  -> 12345678912340000

**Comment by ksgr** [comment]
Numerics are not handled properly, generating invalid data if its more then 15 digit number

**Comment by mccabemj** [comment]
@ksgr This is essentially a duplicate of #136 

The output is actually outputting `123456789123456789`. It is excel (I presume you are using) which is taking this number and modifying it. There is nothing we can do.
