### ISSUE TITLE
how to keep leading zero received in string data?

### ISSUE THREAD

**Issue by moonflower25** [react-csv/react-csv#128]
The string key value passed to headers is printed as a number in csv file.
For example, if you passed '011' to headers props, it will be printed as 11 in csv file.

I know this errors that leading zero must be trimmed in excel. and there is an option to avoid this.

How not to trim the leading zero in string value? is there any options in react-csv?

**Comment by sval1406** [comment]
Has this been resolved? I still see this issue, not sure what the work around is

**Comment by mccabemj** [comment]
@sval-react there is no issue here sadly. This library exports a CSV file, and if you see the raw contents of the output, if you put 001, it would output 001. 

It is Excel which is seeing 001 as a number and stripping the zero, not this library.

**Comment by sval-react** [comment]
Is there an option to pass a column as text field. The column have is a combination of string values and numbers which have leading 0s. It oddly formats the column with strings indented to the left and the numbers to the right with stripping the 0s.
Converting the field to text will trick it to behave like string column, so it there any way of passing the datatype? This will help my situation greatly. Thanks!

**Comment by mccabemj** [comment]
@sval-react There is no way of telling Excel how to format their columns. A CSV file is essentially a text file.

However, one trick you could do would be to put `=""` before the text and an extra two quote after. For example

```
const csvData = [
    {
      firstname: '=""001""',
      lastname: 'me',
      email: 'me@something.com'
    },
  ];
```

You won't see those extra characters

**Comment by sval-react** [comment]
My data is coming from an array.. So I tried this -  "="+""+customer.manufacturer_no+"" and the string values are coming like this-

0
0
#NAME?

And if I try typeof customer.manufacturer_no === "number"? "="+""+customer.manufacturer_no+"": retailer.manufacturer_no then I get the same as previous results with leading 0s stripped and strings formatting to left and numbers formatting to right-
Not sure what I am doing wrong here

B00389
     350587
66A9035

**Comment by mccabemj** [comment]
@sval-react this is a general string concatenation question. Do something like

`'=""' + customer.manufacturer_no + '""'` (notice I am using single quotes to surround the double quotes I said to add)

Or use template literals

**Comment by sval-react** [comment]
It worked out perfectly! Thank you so much for helping out!!

**Comment by teknosains** [comment]
for those using MUI Datagrid for CSV export, to keep leading zero in a string (eg Phonenumber etc), we can use this

```javascript
const columns: GridColDef[] = [
  { 
    field: 'phone', 
    headerName: 'Phone',  
    valueGetter: (params) => {
      return `=CONCATENATE("0",${params.row.phone})`
    },
    renderCell: (params) => {
      return params.row.phone
    },
  }
]
```

this will display normal format in Datagrid and keep the leading zero in the exported CSV.

**Comment by aakashtwinleaves** [comment]
how to do this in java
