### ISSUE TITLE
I need example for API Get JSON for data={data} in CSVLINK

### ISSUE THREAD

**Issue by aa6my** [react-csv/react-csv#134]
error
`checkPropTypes.js:19 Warning: Failed prop type: Invalid prop data supplied to CSVLink.`

InspectorTracking.js (have an issue that i dont know how debug)

```
  renderButton = () => {
    const data = api.getInspectionTracking();
    return (
      

        <div style={{textAlign:'right', marginTop: '25px', marginBottom: '10px'}}>
          <CSVLink 
            data={data}
            filename={"Inspector Tracking Report.csv"}>
              <Button style={{ marginRight: 8 }} block>Export</Button>
          </CSVLink>
          <Button block>Print</Button>
        </div>
    );
  }
```

fetch.js (others ok)
```
import { fetchAPI } from './fetch';
export const getInspectionTracking = async () => {
  return await fetchAPI(`/inspections/tracking`);
}
```

My target only to api get json -> as data array, so data={data} can generate csv

**Comment by aa6my** [comment]
I got the data but
`Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`

**Comment by SimonChris** [comment]
`fetchApi` returns a promise, not the actual data. You need to await the promise to get the data. Try something like this:

```
<CSVLink
  data={this.state.data}
  asyncOnClick={true}
  onClick={async (event, done) => {
    const data = await api.getInspectionTracking();
    this.setState({ data: }, () => done());
  }}
>
```

**Comment by mccabemj** [comment]
@SimonChris is right, good catch. Closing issue
