### ISSUE TITLE
Numbers get converted to scientific notation in excel

### ISSUE THREAD

**Issue by Pixelatex** [react-csv/react-csv#136]
Is there a way we can define a column as 'text' or another way?

I have long 15 digit + codes that look like 468768768833943384.

This gets converted to something like 4,687E+11... the scientific notation. 

Is there nothing I can do about this?

**Comment by mccabemj** [comment]
@Pixelatex it is your spreadsheet application making that change. I presume the outputted data from this library is correct, its just the application displaying it differently (same as many other issues like trimming zeros)

We can't define what column type Excel (for example) should choose, its a limitation of csv files

**Comment by payalkherajani** [comment]
Thankyou! This helped
