### ISSUE TITLE
24Hr time format in windows! 

### ISSUE THREAD

**Issue by PavanKumarRao** [react-csv/react-csv#140]

**Comment by mccabemj** [comment]
@PavanKumarRao if this is a feature request, can you provide more details please

**Comment by PavanKumarRao** [comment]
![img_20190207_180222](https://user-images.githubusercontent.com/43343085/52411718-b9e17400-2b02-11e9-9582-29e10eaf8634.jpg)

**Comment by PavanKumarRao** [comment]
can u see the schedule column where time is shown in 24hr format, how do i make it 12 hr format?
Thnaks for replying back

**Comment by mriccid** [comment]
This library doesn't format columns with times or dates in them. This looks like it's Excel's formatting. Are you able to provide some of the raw values from the CSV for the "SCHEDULE" column?

**Comment by mccabemj** [comment]
@PavanKumarRao as mriccid said, this library doesn't format the data for you, it is excel formatting it here. I suggest modifying the data first (into a string format you prefer) before inserting, although you still may have an issue of excel changing it. Its outside the scope of this package however.
