### ISSUE TITLE
Add Release notes

### ISSUE THREAD

**Issue by rlreamy** [react-csv/react-csv#143]
As a developer I want to review what changes have happened to libraries I am using. so that I can determine if I need to upgrade it, and what kinds of issues I might encounter if I do.

This can be achieved either by tagging your releases and adding information about what was in the release, or by adding a Changelog.

**Comment by mccabemj** [comment]
@rlreamy is this not sufficient? - https://github.com/react-csv/react-csv/releases

**Comment by rlreamy** [comment]
Sorry, I am not sure how I missed that...
You are golden!  Thanks!
