### ISSUE TITLE
Boolean 'false' value is blank in csv

### ISSUE THREAD

**Issue by tejaswinieswar** [react-csv/react-csv#145]
Hi,

My JSON data has boolean fields. When the value is 'false' the CSV file has blank value for it. For 'true' value the CSV has correct data.

I believe this line could be the reason for this -> https://github.com/react-csv/react-csv/blob/master/src/core.js#L50

 Is there a work around for this? Thank you!

**Comment by mccabemj** [comment]
@tejaswinieswar Agree this is an issue and you are right about the place in the code. @codeewander hsa submitted a PR that I believe will sort it out. When that gets modified and approved it should be good to go

**Comment by AndreVizosodaCruz** [comment]
Hello, the problem when is false getting a blank field in exported csv is already resolved?

**Comment by incarnateTheGreat** [comment]
+1. This still exists.

**Comment by sameerpanicker** [comment]
+1

**Comment by carvalhods** [comment]
+1

**Comment by QuantumTarantino** [comment]
+1

**Comment by themroh** [comment]
+1

**Comment by thatPranav** [comment]
+1

**Comment by blopa** [comment]
+1

**Comment by patsongco** [comment]
+1
