### ISSUE TITLE
BOM on IE11

### ISSUE THREAD

**Issue by aklein-dex** [react-csv/react-csv#146]
When downloading a csv file with IE11, the BOM is not included despite using args uFEFF.

It seems in Link.js, there is a function only for IE named handleLegacy(), and this doesn't check if uFEFF is set. Is it possible to fix it?

On Chrome it works as expected.

**Comment by aklein-dex** [comment]
sorry, I just saw there is already a PR (https://github.com/react-csv/react-csv/pull/86) for that.

**Comment by mccabemj** [comment]
Fixed in v.1.1.2
