### ISSUE TITLE
Consider adding TypeScript support

### ISSUE THREAD

**Issue by vincentjames501** [react-csv/react-csv#147]
We just started using react-csv and it suits our needs well. We've had to manually declare some type definitions for usage with TS and would be great if this lib exported TypeScript definitions. Otherwise, we may make an MR sometime soon over to DefinitelyTyped. Just logging this here to let people know there is interest in TS support!

**Comment by Antonhansel** [comment]
Hey @vincentjames501,

I'm interested, can you share the type definitions you have for now ?

**Comment by vincentjames501** [comment]
I put together a first pass over here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33634 .

Feel free to test them out and give it a go. I didn't export the things in `core` for the first pass.

**Comment by vincentjames501** [comment]
Just thought I'd mention that the types have been published and appear to be working fine. I didn't export things in `core` as I didn't want to mess up the types. If maintainers add some docs to those exported functions to document what they are expecting I'd be happy to add the rest.

**Comment by vincentjames501** [comment]
I'm going to close as they have been published and working for us.
