### ISSUE TITLE
Ability to show an icon instead of the 'Download Me' text react-csv

### ISSUE THREAD

**Issue by jdhanesh** [react-csv/react-csv#148]
Hi,

I would like to use a font-awesome or some other icon instead of the 'Download Me' text in reac-csv. 
Can this be done ?

**Comment by Cyan005** [comment]
When I put this together, I used an Excel-like image within the component similar to:

```
<CSVLink data={this.state.items} headers={ CSVHeaders.getWorkplaceAutomationHeaders()} filename={'XYZ.csv'}>
      <img src={require('./excel.png')} className={ styles.excelImg } />
</CSVLink>
```

**Comment by mriccid** [comment]
You should be able to render whatever you want within the `CSVLink` component. However, if anything interferes with the click events propagation you might run into problems
