### ISSUE TITLE
Unable to export csv with drop-down option in one column and hide one column

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [react-csv/react-csv#157]
I want to export the CSV file from the object/array where in my array i am having two fields as boolean which i want to be converted into select options in excel(or radio etc).
Exp Data: [{
"Id":112,
"Name":"Abhay",
"canSpeakHindi": true,
"canSpeakEnglish": true,
"Phone":00000000
}]
Once user download excel he/she will get excel with id as hidden column and boolean will be converted into Yes/No. User can change Yes to No ie "true to false" and upload csv back.

I am unable to convert boolean values into options/radio etc so user can change them and save file.

Also want to add restriction on file that only users can change option and not any text in row/columns

**Comment by mccabemj** [comment]
@AbhaysinghBhosale This library is exporting a CSV file (which is essentially a plain text file with commas in in). All the things you require are things that a spreadsheet application would provide, not this library.
