### ISSUE TITLE
Linux sees files as plainText instead of CSV format by default?

### ISSUE THREAD

**Issue by kDurg** [react-csv/react-csv#158]
When exporting a file, it seems that both windows and mac's are able to open the files in their default spreadsheet programs, though for some reason Linux is only opening them in plain text format. I have added a .csv to the end of the filename, though it still shows up as a plaintext file. Is there something I am missing or is anyone else able to replicate this issue? Thanks!

**Comment by kDurg** [comment]
![Image Pasted at 2019-5-8 10-53 (1)](https://user-images.githubusercontent.com/43588210/57393186-d16ede00-717f-11e9-84d8-2010909e8178.png)
![Image Pasted at 2019-5-8 10-53](https://user-images.githubusercontent.com/43588210/57393189-d338a180-717f-11e9-96ef-aa88195a87fa.png)

**Comment by mccabemj** [comment]
@kDurg are you using `CSVLink` or `CSVDownload`? I am not experiencing the same thing, although I am also struggling to get an export without a .csv extension.

Let us know your browser and specific OS version along with the above question

**Comment by kDurg** [comment]
I was using CSVDownload, though it seems like it was acting fine afterall. Just a weird issue on our end. Thanks for checking in. I will close this out.
