### ISSUE TITLE
react-csv seems to combine 2 array items into 1 row

### ISSUE THREAD

**Issue by AM1467** [react-csv/react-csv#159]
Hello, I recently imported react-csv in my project with the following array of header + data:

Array(6) [Array(1), Array(1), Array(1), Array(1), Array(1), Array(1)]
EditTranscoding.js:162
length:6
```
__proto__:Array(0) [, …]
0:Array(1) ["Column A;""Component B"]
1:Array(1) ["F;""C""]
2:Array(1) ["HP;""N""]
3:Array(1) ["TP;""S""]
4:Array(1) ["W;""W""]
5:Array(1) ["XZ;""X""]
```

expecting to get a CSV with one column and 5 rows. However, the result is:

![image](https://user-images.githubusercontent.com/14926899/58026390-0afbfd80-7b1f-11e9-8344-87b183715015.png)

As you can see, the first 2 array items are in the same cell, same goes for the rest of them. I tried with the original example in the docs and everything works fine. So I suppose there is something wrong with my String formatting. I have inserted some escaped quotes and ";" which need to be there for a reason. Any help greatly appreciated.

**Comment by mccabemj** [comment]
@AM1467 The raw data you have there is not valid on its own in JavaScript, so its hard to know how your original data started and I don't know where its coming from.

Are you saying your original data is exactly as above, so this would be the equivalent;

```
  [
    ['"Column A;""Component B"'],
    ['"F;""C""'],
    ['"HP;""N""'],
    ['"TP;""S""'],
    ['"W;""W""'],
    ['"XZ;""X""']
  ];
```

Or have you quoted around the data, so its more like this

```
[
    ['Column A;""Component B'],
    ['F;""C"'],
    ['HP;""N"'],
    ['TP;""S"'],
    ['W;""W"'],
    ['XZ;""X"']
  ];
```
