### ISSUE TITLE
CSVLink does not work for firefox

### ISSUE THREAD

**Issue by xiacijie** [react-csv/react-csv#161]

**Comment by landonwilkins** [comment]
Can't repro, works for me in Firefox.

OS X: 10.13.6
Firefox: 66.0.3 (64-bit)

**Comment by mccabemj** [comment]
@xiacijie Seems to be working fine for any variation of Firefox I have. Please re-open if still an issue, along with the version of firefox and OS

**Comment by waltherg** [comment]
Doesn't work on

Firefox 60.6.1ers
OSX 10.13.3

No reaction from the browser when clicking a corresponding download link.
