### ISSUE TITLE
Detect download

### ISSUE THREAD

**Issue by anllyksell** [react-csv/react-csv#163]
Hello,

First of all, thank you for this library. I'm using it in an react-electron project. I'm trying to detect download so when download is done, I want to show a popup or notification. But I want to user about it. Is there way about it ?? Any event maybe ??

**Comment by mccabemj** [comment]
@anllyksell This library is not really intended for Electron use (even though I am aware of people using it).

Perhaps this could help you to notify when electron downloads are done - [https://electronjs.org/docs/api/download-item#event-done](https://electronjs.org/docs/api/download-item#event-done)
