### ISSUE TITLE
CSV file just contains HTML from index.html

### ISSUE THREAD

**Issue by CallumHemsley** [react-csv/react-csv#168]
Here is my code below. I successfully arrange CSVLink to only be 'clicked' once the data has been fetched like issue #72 . However, upon downloading the file, and opening it in excel, or notepad ++ etc.. all I see is HTML of the index.html page. When doing `console.log(this.state.newJobs)` I get the intended rows. Any ideas?

`exportCSV = jobs => {
  this.setState({ newJobs: jobs }, () => {
    // click the CSVLink component to trigger the CSV download
    this.csvLink.current.link.click();
  });
};`

`render() {
  console.log(this.state.newJobs);
  return (
    <DropdownButton id="dropdown-basic-button" title="Export">
      <div onClick={() => this.requestRows("CSV")}>
        <Dropdown.Item>CSV</Dropdown.Item>
      </div>

      {this.state.newJobs.length ? (
        <CSVLink
          data={this.state.newJobs}
          filename="jobs.csv"
          className="hidden"
          ref={this.csvLink}
          target="_blank"
        />
      ) : null}`

**Comment by CallumHemsley** [comment]
Formatting of code doesn't seem to want to work...

**Comment by CallumHemsley** [comment]
Using PapaParse, closing this since no response.

**Comment by Jobbalob** [comment]
Understand this is closed now but for anyone else with this problem, I found that it occurred when the ref to the CSVLink was not fully instantiated for some reason.

To fix for functional components, I added a second useEffect, triggered by the first useEffect checking the link is ready. I think the second render just ensures the ref is valid, but I'm no expert. Here's the code:

`React.useEffect(() => {
        if (exportButton.current !== undefined) {
            if(exportButton.current.link
                && exportButton.current.link.click
                && typeof exportButton.current.link.click == 'function'
            ) {
                setLinkReady(true);
            }
        }
        
    }, [exportButton])

    React.useEffect(() => {
        if (exportButton.current !== undefined) {
            if(exportButton.current.link
                && exportButton.current.link.click
                && typeof exportButton.current.link.click == 'function'
            ) {
                if (linkReady) {
                    exportButton.current.link.click();
                }
            }
        }
        
    }, [exportButton,linkReady])`
