### ISSUE TITLE
Format custom Json to csv

### ISSUE THREAD

**Issue by ParmentierChristophe** [react-csv/react-csv#171]
hi ! 

the back end returns to me this Json:

```
    {
      countryCodes: ['fr', 'gb', 'us'],
      nbValidPhoneNumbers: 2,
      inValidPhoneNumbers: [
        {
          phoneNumber: '+0987654321',
          countryCode: 'be'
        },
        {
          phoneNumber: '+124567890',
          countryCode: 'fr'
        }
      ]
    }
```

I need to export that in the best way, do you have an idea to help me?

**Comment by mccabemj** [comment]
Hi. Thanks for the issue, however it’s not really an issue with the repo, more a coding question. The docs outline the format of data that is required, so if you look into JavaScripts ‘map()’ functionality, it should help you get the data in the format you need
