### ISSUE TITLE
No support? Dead repo? Not usable

### ISSUE THREAD

**Issue by jaketrimble** [react-csv/react-csv#172]
Do not use this repo. Owner doesn’t respond to messages or issues and the download doesn’t work for Windows...you know, the largest subset of computers on the planet.

**Comment by mccabemj** [comment]
@jaketrimble - https://www.google.co.uk/amp/s/nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/amp/

If you have an issue, please try and explain it concisely to get assistance. If not, your issue serves no purpose. 

If you are a developer, why not help out? Help fix the issues you are facing. This is open source. No one is getting paid. We are all doing it for each other.

**Comment by jaketrimble** [comment]
@mccabemj So what you are saying is that in this open source community, I should not be able to warn other developers of the issues this repo has? Maintenance and support in open source repos is critical to adoption in projects and this repo seems to have none of it. The issue I created is the issue _I_ have with this repo and for me and hopefully others has served its purpose. I get that being a maintainer can be difficult, but if that's the case then state in the readme that support and maintenance for this repo is extremely limited, like other maintainers do. Thanks for getting back to me.
