### ISSUE TITLE
Webpack compile failed

### ISSUE THREAD

**Issue by a2441918** [react-csv/react-csv#173]
![image](https://user-images.githubusercontent.com/4927454/65004862-e5fc7900-d8cb-11e9-8033-bc9c6f4c532d.png)

Get this issue when I compile my app using webpack. Anything I'm missing?

Boilerplate I used: https://github.com/react-boilerplate/react-boilerplate

Works great with the default boilerplate but has above issues when I use my code in the boilerplate.

**Comment by JordanW7** [comment]
See https://github.com/react-csv/react-csv/issues/71

This worked for me

**Comment by a2441918** [comment]
Thanks. Worked for me.
