### ISSUE TITLE
Support for nested headers

### ISSUE THREAD

**Issue by webmastervishal** [react-csv/react-csv#175]
I have been trying to create a nested header like the below 

![image](https://user-images.githubusercontent.com/15266438/65226930-62b66f80-dae5-11e9-9510-24687a127864.png)

Here contact is main column, whereas mobile and email are the child columns.
I am not getting a way with react-csv to do this.

Please help me to achieve this.

**Comment by webmastervishal** [comment]
seems like no one is there to maintain this library ;)

**Comment by mccabemj** [comment]
@webmastervishal what you are describing is not a valid CSV file. This is to create a CSV file, not a speadsheet/Excel file.

**Comment by joshuafernandes1996** [comment]
Any wordaround for it?

**Comment by Jay-zalavadia** [comment]
@mccabemj @webmastervishal were you able to achieve it? If yes can you share the sample for it?
