### ISSUE TITLE
dot notation for `key` in headers stopped working

### ISSUE THREAD

**Issue by Oodmincheg** [react-csv/react-csv#180]
Hello. After update package from 1.0.14 to 1.1.1 all columns with dot notation keys stopped working. 
There is my headers: 
{label: "#WO", key: "number"}
1: {label: "Property #", key: "propertyId"}
2: {label: "Property Name", key: "_original.propertyExtended.name"}
3: {label: "PM", key: "_original.propertyManager.name"}
4: {label: "Sub", key: "sub"}
5: {label: "Priority", key: "priority"}
6: {label: "Status", key: "_original.status"}
7: {label: "Created", key: "_original.timeCreated"}
8: {label: "Due", key: "timeDue"}
9: {label: "Completed", key: "timeCompleted"}
10: {label: "Reporter", key: "_original.ownedBy.name"}
11: {label: "Reported by", key: "_original.reportedName"}
12: {label: "Reported by Type", key: "_original.reportedType"}
13: {label: "Reported by Contact #", key: "_original.reportedContact"}
14: {label: "Room", key: "_original.room"}
15: {label: "Description Category", key: "descriptionCategory"}
16: {label: "Description", key: "description"}
17: {label: "Work Required", key: "_original.workRequired"}
18: {label: "Work Completed", key: "_original.workCompleted"}
19: {label: "Internal Comments", key: "_original.internalComments"}
and my data
description: "Owners List (updated 9/3)-open fire pit in spring"
descriptionCategory: "Exterior Issues"
number: "138439"
priority: "normal"
propertyId: "RUBYWOOD"
sub: "Kyle Fyock"
timeCompleted: "05/20/2017"
timeDue: "05/20/2017"
_original.internalComments: "Oakleys.. "
_original.ownedBy.name: "Dustin   Johnson"
_original.propertyExtended.name: "Rubywood"
_original.propertyManager.name: "Dustin   Johnson"
_original.reportedContact: ""
_original.reportedName: "Julie Pahl"
_original.reportedType: "Owner"
_original.room: ""
_original.status: "in progress"
_original.timeCreated: "04/30/2016"
_original.workCompleted: ""
_original.workRequired: "Paint the pole from the new heat tape so as to match the 
All works fine with 1.0.14. Support of dota notation still here in 1.1.1? If yes what I'm doing wrong.

**Comment by tegranjeet** [comment]
Hello, I am also experiencing this issue. Have you found a way around it?

Getting error `TypeError: null is on an object (evaluation o[p]`

Thanks.

**Comment by Oodmincheg** [comment]
No :( We decided to stay on working(at least for us) version.

**Comment by tegranjeet** [comment]
Interesting, version 1.0.14 wasn't working for me either.

**Comment by tegranjeet** [comment]
Just opened a pull request to fix this issue that is still present on 2.0.1

**Comment by abdennour** [comment]
PR is merged. And issue is fixed since **react-csv@2.1.9**

Thank you @tegranjeet !
