### ISSUE TITLE
Preserving leading Zero in csv file

### ISSUE THREAD

**Issue by marcorag** [react-csv/react-csv#181]
i tried to preserve the leading zero in csv file but is impossible.
there is any props or workaround to obtain this or is a real issue?

**Comment by hmudimi** [comment]
@marcorag Please provide some sample data values or a fiddle to reproduce this issue.

**Comment by marcorag** [comment]
i attached an example image.

![70942700_1310703719099404_1786617137125654528_n](https://user-images.githubusercontent.com/15266375/68205054-997b1300-ffc9-11e9-8e73-56a68a44ec27.png)

**Comment by AhmedSaeedAS** [comment]
use (String.fromCharCode) , it worked for me 
"Contact Number": item.contactNumber + String.fromCharCode(8203)

**Comment by AhmedSaeedAS** [comment]
> use (String.fromCharCode) , it worked for me
> "Contact Number": item.contactNumber + String.fromCharCode(8203)

Well this is not the library issue. This is due to some setting of excel, which prevent you to add zero before any number

**Comment by mccabemj** [comment]
@marcorag this is Excel removing the zero. Unless the core CSV has the zero missing (open in a text editor) then its not really the libraries issue.

See here for more info and a workaround - https://github.com/react-csv/react-csv/issues/164
