### ISSUE TITLE
React upgrading

### ISSUE THREAD

**Issue by NicoLaval** [react-csv/react-csv#182]
Will the lib get a release soon on React version?
16.+ apps don't support `componentWillReceiveProps`

**Comment by Exonalex** [comment]
have same issue. `componentWillReceiveProps` is deprecated. Need a update

**Comment by abdennour** [comment]
@mccabemj  What do you think ? when can  we release with support of React +16 ?

**Comment by kartouch** [comment]
Any update on this? thx

**Comment by mccabemj** [comment]
Would love some help on this if anyone is available

**Comment by adriancova** [comment]
Do you still need help with this? I could work on this during the weekend.

**Comment by MomoRazor** [comment]
Would also like an update on this, might attempt a fix if your still looking for help

**Comment by johnnyreilly** [comment]
If those people who have capacity to help are up for having a go, maybe this could move forward?  Have a crack at it I say!

**Comment by kartouch** [comment]
I've submitted a PR for this.
