### ISSUE TITLE
Displaying images in CSV cells

### ISSUE THREAD

**Issue by MarianneAK** [react-csv/react-csv#197]
I couldn't figure how to export images into the CSV using react-csv. Is there a way to do that ?

**Comment by pzi** [comment]
@MarianneAK Given CSV is just text, you would have to convert images to base64 I suppose?

**Comment by mccabemj** [comment]
@MarianneAK this package is for CSV files, and as @pzi said, it is only for raw text. If you wanted the CSV file to store the data, you can convert the image to base64. However, I presume you want to open in Excel or some other program to view the image and this library can't and will never do that
