### ISSUE TITLE
How to extend the size of row and column using this react-csv 

### ISSUE THREAD

**Issue by nani1232** [react-csv/react-csv#200]
It just defaults to some 8.09 px size and I don’t know how to Increase the size of each cells, can some one help me in that? 

Note:
I don’t see any option increase the cells for both row and column width

**Comment by briandelancey** [comment]
Unless I'm not understanding your question, you aren't able specify/change formatting because the .CSV format contains no display information. It's data only.

**Comment by nani1232** [comment]
Okay! Is there any way that we can handle the cell size and data both at a time by using any other frameworks like react-csv, would u be able to suggest?

**Comment by abdennour** [comment]
Thanks @nani1232  for your suggestion. 

However, You can't... a CSV file has no formatting of any kind, including column size.

If you want to control column widths, then you need to write the data to a format that does support columns widths, such as BIFF (.xls) or OfficeOpenXML (.xlsx) or OASIS Open Document Format (.ods) or Gnumeric or other spreadsheet.

REFERENCE : https://stackoverflow.com/questions/15224052/how-to-set-size-of-column-of-csv-file
