### ISSUE TITLE
How can Download data with nexted array?

### ISSUE THREAD

**Issue by vishnusinghchauhan** [react-csv/react-csv#214]
Hello All,

Can anyone help me to download CSV with Nexted Array?

{

    "name" : "rohit",
    "email" : "rohit@gmail.com",
    "phone" : "123",
    "activity_array" : [ 
        {
            "activity_desc" : "First time Registration",
            "activity_title" : "User Registration",
        }, 
        {
            "activity_desc" : "fadsf\nadsf\nadsf\nsa\nf\nsf\nsdf",
            "activity_title" : "reagarding salary",
        }, 
        {
            "activity_desc" : "adfa",
            "activity_title" : "fanl",
        }
    ]
}

**Comment by kerrande** [comment]
Had to flatten a complex object into a simple json array. 
From this:
```
"name" : "rohit",
"email" : "rohit@gmail.com",
"phone" : "123",
"activity_array" : [ 
    {
        "activity_desc" : "First time Registration",
        "activity_title" : "User Registration",
    }, 
    {
        "activity_desc" : "fadsf\nadsf\nadsf\nsa\nf\nsf\nsdf",
        "activity_title" : "reagarding salary",
    }, 
    {
        "activity_desc" : "adfa",
        "activity_title" : "fanl",
    }
]
```
To this:
```
[
    {
          "name":"rohit", 
          "email" : "rohit@gmail.com",
          "phone" : "123",
          "activity_desc":"First time Registration",
          "activity_title" : "User Registration"
    },
    {
          "name":"rohit", 
          "email" : "rohit@gmail.com",
          "phone" : "123",
          "activity_desc": "fadsf\nadsf\nadsf\nsa\nf\nsf\nsdf",
          "activity_title" : "reagarding salary"
    },
    {
          "name":"rohit", 
          "email" : "rohit@gmail.com",
          "phone" : "123",
          "activity_desc":"adfa",
          "activity_title" : "fanl"
    }
]
```
with something like this:
```
const stateToCSV=()=>{
    var temp=[]
    for(var i =0;i< data.length;i++){
        for(var j =0;j<data[i].activity_array.length;j++){
            temp.push({
                "name":data[i].name, 
                "email" :data[i].email,
                "phone" : data[i].phone,
                "activity_desc":data[i].activity_desc[j].activity_desc,
                "activity_title" : data[i].activity_desc[j].activity_title
            })
        }
    }
    return temp
}
```
The above fix is temporary and unique to this datatype so it would be more useful to take a look at the repo [here](https://github.com/deedubs/flatten-json)

**Comment by kerrande** [comment]
I found it! The library is called [lodash](https://lodash.com/docs/4.17.15) and although it might be complicated to learn the functions involved, you could probably derive an easier solution than mine with it.

**Comment by mccabemj** [comment]
@vishnusinghchauhan @kerrande is right, you have to flatten the data to pass in
