### ISSUE TITLE
Error while export mobile number

### ISSUE THREAD

**Issue by JasirMJ** [react-csv/react-csv#217]
![WhatsApp Image 2020-04-15 at 12 47 14 PM](https://user-images.githubusercontent.com/29107085/79309519-0ea72880-7f18-11ea-8b6e-9563b5e2d60e.jpeg)

im using win10

**Comment by mccabemj** [comment]
@JasirMJ this is how Excel renders certain numbers. Open in a text editor and you will probably see the raw data is fine. This issue gives a work around if needed - https://github.com/react-csv/react-csv/issues/164
