### ISSUE TITLE
Loading data asynchronously and downloading CSV data with a click is one step behind the latest retrieved data

### ISSUE THREAD

**Issue by codeamo** [react-csv/react-csv#221]
I am loading data asynchronously and then trying to download the retrieved data from the server with one click. The problem I am currently facing is that the click is a step behind the current state. When the component first renders it downloads an empty CSV file and on the second click it downloads the data from the previous fetch, not the current/latest fetch. 

Here is my code as of now: 
**Download button**
`  <Button onClick={() => handleCsvExport()}>Download</Button>
    <CSVLink
        filename="MY-FILE.csv"
        data={downloadData}
        ref={csvLink}
        target="_blank"
    />`
**API fetch**
` const handleCsvExport = () => {
    fetch('api_link')
      .then((resp) => setDownloadData(resp));
  };`

**Comment by VBoureaud** [comment]
Hey.
I had the same issue today but i found a way to still using.

When your data is loaded, update your state with your data and a boolean like "ToDownload"
Like that, you can use componentDidUpdate() and catch this.state.toDownload.
If you catch value true, use setState to change toDownload value and in the callback, launch for example this.csvLink.current.link.click().

Not really clean solution but work until fix.

Here an example:
`import React from 'react';
import { CSVLink } from 'react-csv';

class HomeScene extends React.PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      data: [],
      toDownload: false,
    };

    this.csvLink = React.createRef();
    this.handleCsvExport = this.handleCsvExport.bind(this);
  }

  componentDidUpdate() {
    if (this.state.toDownload) {
      this.setState({ toDownload: false }, () => this.csvLink.current.link.click());
    }
  }

  handleCsvExport() {
    // ...
    // async stuff here
    // when you get your newData
    this.setState({
      data : newData,
      toDownload : true,
    });
  }

  render() {
    return (
      <div>
        <Button onClick={this.handleCsvExport}>Download</Button>

        <CSVLink
          data={this.state.data}
          ref={this.csvLink}
          target="_blank"
       />
      </div>
    );
  }
}`

**Comment by codeamo** [comment]
@VBoureaud Thanks for offering your help but I am still having the same problem. let me post more code than I post earlier if maybe the issue is coming from a different part. btw I am using Hooks not a class-based component so setting a state does not accept callbacks FYI. 

```
import React, { useState, useEffect, createRef } from 'react';
import { CSVLink } from 'react-csv';

const HomeScene = () => {
  const [downloadData, setDownloadData] = useState([]);
  const [active, setActive] = useState(false);
  const csvLink = createRef();

  useEffect(() => {
    if (active) {
      setActive(false);
      csvLink.current.link.click();
    }
  }, [downloadData]);

  const handleCsvExport = (id) => {
    //async stuff here and then chain a promise
      .then((response) => setDownloadData(response), setActive(true));
  };

  return (
    <div>
      <Button onClick={() => handleCsvExport(id)}>Download</Button>

      <CSVLink data={downloadData} ref={csvLink} target="_blank" />
    </div>
  );
};
```

**Comment by codeamo** [comment]
ok, I figured out. I think the problem was coming from when I was setting the download data state inside the promise. everything else is correct. just changed 
```
 const handleCsvExport = (id) => {
    //async stuff here and then chain a promise
      .then((response) => setDownloadData(response), setActive(true));
  };
```
TO 

```
 const handleCsvExport = (id) => {
    //async stuff here and then chain a promise
      then((resp) => {
      setDownloadData(resp.payrollDetails);
      setActive(true);
    });
  };
```
If anyone is having this issue you can also find help on this [ISSUE](https://github.com/react-csv/react-csv/issues/72)

**Comment by ELELUABDULSALAM** [comment]
@codeamo this work 
In case you have useEffect looking out for more than state, you need to use two useEffect.

**Comment by hjrobinson** [comment]
@codeamo
I needed to use something similar to what you used at first like:
```
.then((response) => setDownloadData(response), setActive(true));
```
I also needed to add a setTimeout function the useEffect hook to avoid incomplete data from being passed to the csv file:
```
  useEffect(() => {
    if (active) {
      setActive(false);
      setTimeout(() => {
        csvLink.current.link.click();
      })
    }
  }, [downloadData]);
```
I learned about the timeout idea from here:
https://www.youtube.com/watch?v=o4JOysBWeos

But it can also be found at the end of the ISSUE page you referenced here:
https://github.com/react-csv/react-csv/issues/72

Also in lieu of setting state for active you could just set the initial state for downloadData equal to an empty string like:
```
const [downloadData, setDownloadData] = useState("");
```

Then just run the useEffect hook if there was any data (assuming you start out with no data when rendering the component):
```
 useEffect(() => {
    if (downloadData) {
      setTimeout(() => {
        csvLink.current.link.click();
      })
    }
  }, [downloadData]);
```
But I don't know if that's the best approach since it tests for the presence a null value and could cause problems depending on the structure of your responses.

**Comment by hjrobinson** [comment]
I think I may have found an even better approach that just uses two useEffect hooks. Perhaps this is what ELELUABDULSALAM was eluding to. 

First set the csvData:
```
.then((response) => setDownloadData(response));
```
Then just use two useEffect hooks and test for the length of the array in the first one:
```
  useEffect(() => {
    if(downloadData.length){
      setActive(true);
    }
  },[downloadData]);

  useEffect(() => {
    if(active){
      csvLink.current.link.click();
      setActive(false);
    }
  },[active]);
```

**Comment by mdodge-ecgrow** [comment]
I had the same issue and couldn't figure out codeamo's fix.  I followed other reponses in this thread and that video posted by hjrobinson.

Here was what worked for me:

```js
const CSVReportLink = React.createRef();

useEffect(() => {
	if (reportData.length > 0) {
		CSVReportLink.current.link.click();
		setLoading(false);
	}
}, [reportData]);

const getReport = async () => {
	if (!loading) {
		setLoading(true);
	}
	const reportDataRes = (
		await getUsersReport({
			type: reportType,
			fields: checkedUserFields,
			userTypes: checkedUserTypes,
			sortFields,
			firstUserSortType
		})
	).data?.reportData;
	setReportData(reportDataRes);
};
...
<button className={'btn btn-primary'} onClick={getReport}>
	{loading ? 'Loading csv...' : 'Download CSV Report'}
</button>
<CSVLink
	data={reportData}
	// uFEFF={false}
	ref={CSVReportLink}
	filename={`${reportType}-Report`}
/>
```

**Comment by dmikester1** [comment]
I had the same issue and couldn't figure out codeamo's fix.  I followed other reponses in this thread and that video posted by hjrobinson.

Here was what worked for me:

```js
const CSVReportLink = React.createRef();

useEffect(() => {
	if (reportData.length > 0) {
		CSVReportLink.current.link.click();
		setLoading(false);
	}
}, [reportData]);

const getReport = async () => {
	if (!loading) {
		setLoading(true);
	}
	const reportDataRes = (
		await getUsersReport({
			type: reportType,
			fields: checkedUserFields,
			userTypes: checkedUserTypes,
			sortFields,
			firstUserSortType
		})
	).data?.reportData;
	setReportData(reportDataRes);
};
...
<button className={'btn btn-primary'} onClick={getReport}>
	{loading ? 'Loading csv...' : 'Download CSV Report'}
</button>
<CSVLink
	data={reportData}
	// uFEFF={false}
	ref={CSVReportLink}
	filename={`${reportType}-Report`}
/>
```

**Comment by VedanshWebmobi** [comment]
> @VBoureaud Thanks for offering your help but I am still having the same problem. let me post more code than I post earlier if maybe the issue is coming from a different part. btw I am using Hooks not a class-based component so setting a state does not accept callbacks FYI.
> 
> ```
> import React, { useState, useEffect, createRef } from 'react';
> import { CSVLink } from 'react-csv';
> 
> const HomeScene = () => {
>   const [downloadData, setDownloadData] = useState([]);
>   const [active, setActive] = useState(false);
>   const csvLink = createRef();
> 
>   useEffect(() => {
>     if (active) {
>       setActive(false);
>       csvLink.current.link.click();
>     }
>   }, [downloadData]);
> 
>   const handleCsvExport = (id) => {
>     //async stuff here and then chain a promise
>       .then((response) => setDownloadData(response), setActive(true));
>   };
> 
>   return (
>     <div>
>       <Button onClick={() => handleCsvExport(id)}>Download</Button>
> 
>       <CSVLink data={downloadData} ref={csvLink} target="_blank" />
>     </div>
>   );
> };
> ```

This worked Thanks mate
