### ISSUE TITLE
CSVDownload

### ISSUE THREAD

**Issue by lieyongchang** [react-csv/react-csv#227]
is the feature to add filename added ? as currently it is downloading with random filename with no csv extension. 

What I have tried:
`return <CSVLink data={data} filename="text.csv" />` This is added at the end of a functional component, but nothing happens. Any suggestion on where I did wrong and how I could solve it will be much appreciated.

**Comment by marclundgren** [comment]
> <CSVLink

@lieyongchang did you mean `<CSVDownload` ? If so, I'm experiencing the same problem. However, if I change it to a`CSVLink` and click it, the filename will appear as expected.

**Comment by lieyongchang** [comment]
I did a work around by using other library. But thanks for replying :)
