### ISSUE TITLE
PR: Load data once async click has called done()

### ISSUE THREAD

**Issue by dajomu** [react-csv/react-csv#239]
Hi,
I've been working with this component, but wanted to download data on click, then save when the data has been loaded asynchronously and download an csv file with the new data when done() is called.
The async click can be seen in example three here -
https://github.com/react-csv/react-csv#--onclick-props

I've added a PR that allows data to be a function that is only called when the component is in async mode:
https://github.com/react-csv/react-csv/pull/238

I.e I can update my state with new loaded data, then call done in the onClick, then allow that data to be loaded into the csv with a function.

**Comment by abdennour** [comment]
Great feature @dajomu  !
I will try to add more unit tests. But if you could do it, it will be appreciated

**Comment by abdennour** [comment]
Awesome ! CI is passing https://github.com/react-csv/react-csv/runs/4577316919?check_suite_focus=true

**Comment by abdennour** [comment]
Released with react-csv@2.1.8
