### ISSUE TITLE
Component CSVLink not apply "enclosingCharacter", after firing "componentDidUpdate"

### ISSUE THREAD

**Issue by dieuit07** [react-csv/react-csv#241]
Hi guys, it's still not working. Let keep continuing with this issue
https://github.com/react-csv/react-csv/issues/68

 After debugging the code, I figure out, inside the file "**src/components/Link.js**"  block "**componentDidUpdate**" of component "**CSVLink**" , the props "**enclosingCharacter**" doesn't pass to function "**this.buildURI(data, uFEFF, headers, separator)**"

Hence, the URL at the first render will work with "**enclosingCharacter**", but don't work with after "**updating state**"

I wonder if there's any pull-request about this little issue. If it's not, I'm very pleased to help.

**Comment by glinkot** [comment]
Yes, I've got the surrounding characters coming back too.  Any chance of a fix to this one?

**Comment by abdennour** [comment]
Fixed since version v2.1.7
