### ISSUE TITLE
Can't set label for CSVDownload

### ISSUE THREAD

**Issue by ntanwir** [react-csv/react-csv#244]
Just like I can do set a label for `CSVLINK` like this `<CSVLink data={csvData}>Download me</CSVLink>`

How do I achieve same thing for `CSVDownload ` as `<CSVDownload data={csvData} target="_blank" > Download me over</CSVDownload >` does not seem to work.

**Comment by appsmadeforu** [comment]
Try passing headers as a separate prop

**Comment by ntanwir** [comment]
yup, I had figured that out. thanks. Closing it now.
