### ISSUE TITLE
Breaking Change in v2 (componentDidUpdate)

### ISSUE THREAD

**Issue by asooge** [react-csv/react-csv#264]
I have come across a subtle, yet significant breaking change in v2 `CSVLink`  related to the deprecation of `componentWillReceiveProps` in favor of `componentDidUpdate` these methods have slightly different timing which would break our implementation of `CSVLink` building csv files on the fly. Because `componentDidUpdate` executes after the component re-renders, the href in state is not updated until right after the render, causing our downloads to be empty on the first click (second click is completely fine)

To avoid any issues related to timing and lifecycle methods, I would suggest it is better to do this calculation on the fly, inside of the render function, rather than rely on updating state.

**Comment by abdennour** [comment]
Fixed since version v2.1.7
