### ISSUE TITLE
Remove exportation header

### ISSUE THREAD

**Issue by MarceloCavalcanti21** [react-csv/react-csv#267]
Hi!

I would like to know if there is an option to remove the header when I export my array of objects. I would like to receive only the data.

**Comment by ColeBW** [comment]
Any updates to this? I also need to remove headers on export

**Comment by MarceloCavalcanti21** [comment]
Hi, @ColeBW!

I started use another library for satisfaction that condition, the react-csv-downloader.

The implementation is very simple:

`
<CsvDownloader
    filename="MyFile"
    separator=","
    id="CsvDownloader"
    noHeader={true}
    datas={rows}
 />
`
