### ISSUE TITLE
if JSON contains a boolean `false` doesn't get printed in the CSV

### ISSUE THREAD

**Issue by sakshi-choudhary** [react-csv/react-csv#274]
if JSON contains a boolean `false` doesn't get printed in the CSV

```
{
"status": "warning",
"name": "Simulator 1",
"deviceType": "View Sense 1",
"serial": "7a:f1:a4:f7:60:4a",
"deviceId": "f8b1d932ce6b",
"floor": "Floor 4",
"space": "Space 62377",
"commissioned": false
},
```

here in the csv file generated false doesn't show, its blank instead.

<img width="413" alt="Screenshot 2021-04-15 at 13 31 47" src="https://user-images.githubusercontent.com/66865329/114835964-c30bb100-9def-11eb-86ac-000b4dc52c6a.png">

**Comment by ontanj** [comment]
why was this closed? this behaviour caught me today (but when trying to render arrays). it's confusing. either print all booleans or none.
