### ISSUE TITLE
How to add Title to the file?

### ISSUE THREAD

**Issue by navsimransingh** [react-csv/react-csv#275]
<img width="893" alt="2021-04-26 (3)" src="https://user-images.githubusercontent.com/48528875/116112139-4ac1ad00-a685-11eb-93c3-45a5d1fd2c13.png">

I want to add a title to the CSV-generated file. If anyone has some inputs.
Any help is appreciated.

**Comment by QasimRRizvi** [comment]
Does anyone have any idea about this?

**Comment by iamsuzeet** [comment]
@navsimransingh how did you create the excel file with multiple headers as shown in above picture

**Comment by Azrideus** [comment]
you can do this :
```
const csvData=[
			{r1: "REPORTS NOT ACCEPTED", r2: ""},
			{},
			{r1: "Report Date : ", r2: "03-Mar-20"},
			{},
			{r1: "row#", r2: "item"},
			{r1: "1", r2: "lm35"},
		];
```
then remove the headers like this : 
``` 
<CSVLink data={csvData}
		 headers={[
			{key: "r1", label: ""},
			{key: "r2", label: ""},
		  ]}>Download csv</CSVLink>
```

**Comment by navsimransingh** [comment]
Thanks Azrideus

**Comment by yapkm01** [comment]
> Thanks Azrideus

Did it work? I've tried this solution and it does not seem to work with the latest version
