### ISSUE TITLE
data in CSVLink from props.data looks like a static singleton - can not use 2 CSVLinks on the same page

### ISSUE THREAD

**Issue by dorinionescu** [react-csv/react-csv#281]
I added 2 CSVLinks on the same page and I noticed that props.data is shared between the 2 objects
If I dynamically add data to one CSVLink it is written in both props.data
(I checked and the other properties like "filename" are different)
So if I add data to 2 objects, the 2 download links create identical files with the data from the last object updated
The only whey is working is if I 
Add data to first object, immediately download
Add data to the second object, immediately download
Workaround = when you add data to one object, hide "download link" from all the other objects on the page so the user gave up trying to work a lot of files preparing at once and learn that he can not postpone downloading

**Comment by abdennour** [comment]
This issue should be related to your way to manage the state of your application
