### ISSUE TITLE
Handle async data

### ISSUE THREAD

**Issue by DEVASENASYN** [react-csv/react-csv#282]
Hi Im using react-csv to download data as CSV file

Here my data is refreshing for every 3 seconds and manipulating data in service side to export in CSV . So I preferred to download data on button click.  CSVLink is always taking previous data  and exporting them onclick event.. 

I dont want to call api to manipulate data for evey 3 seconds. It should happen on CSVLink button click. Can anyone help me on this?

**Comment by spenweb** [comment]
I recommend this guide: https://www.cluemediator.com/loading-data-asynchronously-and-download-csv-using-react-csv
It worked for me.

**Comment by abdennour** [comment]
Yep! 
Also, by merging the PR #238 , this feature becomes available natively
Just upgrade to react-csv@2.1.8 or later 🎉🎉🎉
