### ISSUE TITLE
Is it possible to merge three columns into one column along with their data?

### ISSUE THREAD

**Issue by Nymisha-Komuravelli** [react-csv/react-csv#289]
I have a table in which three columns are merged into a single column along with the data of three columns. I would like to export this table to csv format. Can someone give any idea on how to achieve this?

**Comment by Azrideus** [comment]
I believe you cant do such a thing in CSV 
you can only save raw data on csv files , any formatting applied to csv files are removed on save

**Comment by abdennour** [comment]
Yep! i confirmed
