### ISSUE TITLE
Filename force replaced from ~ to _

### ISSUE THREAD

**Issue by ChanghyeonYoon** [react-csv/react-csv#291]
I declare filename props to "20210101~20210810_sample.csv'
But downloaded file name is "20210101_20210810_sample.csv'

Also I try to declare file name '~~~~~.csv' but downloaded filename is '_____'

In react-csv is ~ replace to _ ?

**Comment by abdennour** [comment]
Thank you @ChanghyeonYoon for taking time to raise this issue.
This is related to your browser. More insights here https://superuser.com/a/1360801/217352
Happy Reacting :)
