### ISSUE TITLE
Bug - React-CSV not working on SharePoint Mobile App 

### ISSUE THREAD

**Issue by DJoshi23** [react-csv/react-csv#292]
Hello, 

I have created one SPFX Web part with React and use CSVLink for generating the excel sheet.

It's working in mobile chrome browser but if I open the same web part in my mobile Sharepoint App and try to generate the excel sheet that time Sharepoint App crashing.

Code Snippet:

<CSVLink data={this.props.items} filename={'Requests.csv'}>
         <CommandBarButton className={styles.excelbtn} iconProps={{ iconName: 'ExcelLogoInverse' }} text='Export to CSV' > 
      </CommandBarButton> 
</CSVLink>

Thank you in advance

**Comment by abdennour** [comment]
We are not supporting  SharePoint Mobile App
