### ISSUE TITLE
csv downloading two times for onclick.

### ISSUE THREAD

**Issue by nagsky1** [react-csv/react-csv#296]
Given data like these for CSVLink
<CSVLink   ref="SomeRefName"
                data={arr.length == 0 ? CSV_emptyData : arr}
                headers={teststatusheaders}
                filename={"exampleFileName"}
                style={{ display: 'none' }}
            ></CSVLink>

**Comment by thatPranav** [comment]
This happens for me in development build but not in production build.

**Comment by abdennour** [comment]
Issue is fixed. Check comment of @josheilers
