### ISSUE TITLE
Why CSVDownload doesn't support filename prop ?

### ISSUE THREAD

**Issue by kennyma-eplus** [react-csv/react-csv#300]
no one need to rename their CSV file when using CSVDownload ?

**Comment by marrouchi** [comment]
@kennyma-eplus It's possible for you to add "filename" prop.  You may missed that part in the README file : https://github.com/react-csv/react-csv#--filename-props

**Comment by kennyma-eplus** [comment]
> @kennyma-eplus It's possible for you to add "filename" prop. You may missed that part in the README file : https://github.com/react-csv/react-csv#--filename-props

@marrouchi Hi, my question is "CSVDownload" component

**Comment by abdennour** [comment]
hi @kennyma-eplus , There is no direct way to do that.
[All workarounds](https://stackoverflow.com/a/7034818/747579) will show you that you need to put Link behind the scenes.

Thus, if you require filename, use CSVLink component, make it hidden and it triggered when the page is opened.
