### ISSUE TITLE
Getting empty CSV files after upgrading to React 18

### ISSUE THREAD

**Issue by kwalk2108** [react-csv/react-csv#368]
It was working fine with React v17 but now when exporting, I just see empty files. I reverted back to React 17 and it's working again.

Here's the code:

![image](https://github.com/react-csv/react-csv/assets/106088370/749bc604-272b-4e49-8b13-ff68c34a466d)

I confirmed the data is getting to the component and there are no errors.

**Comment by crice88** [comment]
Having the same issue

**Comment by kwalk2108** [comment]
I resolved this issue by adding some logic and to check if the async data populating the CSV had finished downloading and added to the local state prop. Then I used a setTimeout to click the CSV link and open the file. It's not a pretty solution but seems to be getting the job done

**Comment by tommymarshall** [comment]
The primary issue is with using `createRoot` vs `ReactDOM.render`. Switching between how the app is rendered is what triggers the mis-ordered data -- it is always 1 render behind.

**Comment by maduq1** [comment]
> The primary issue is with using `createRoot` vs `ReactDOM.render`. Switching between how the app is rendered is what triggers the mis-ordered data -- it is always 1 render behind.

Exactly this happened to my project. I got the warning https://reactjs.org/link/switch-to-createroot after an update, then applied the change and started having this problem.
