### ISSUE TITLE
Double quotation marks around all values and headers

### ISSUE THREAD

**Issue by asharma327** [react-csv/react-csv#68]
When downloading the CSV, there are double quotation marks around all headers and values. Is there any way to escape these?

**Comment by mriccid** [comment]
Would it help if you could choose which character (or not) is used to wrap each value? e.g. `'`, `"`, `\"`

**Comment by asharma327** [comment]
Yes, immensely!

**Comment by mriccid** [comment]
Great. Would you be interested in creating a PR? If not, I'll make one tonight.

**Comment by asharma327** [comment]
Sure, I will make one

**Comment by asharma327** [comment]
Hey, were you able to get this going?

**Comment by mriccid** [comment]
@asharma327 I've created a PR for changes that will support what you are after

**Comment by tnehme** [comment]
@mriccid - Is this PR implemented?

**Comment by tnehme** [comment]
I dont see it in 1.0.15

**Comment by tnehme** [comment]
var joiner = exports.joiner = function joiner(data) {
  var separator = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : ',';
  return data.map(function (row, index) {
    return row.map(function (element) {
      return "\"" + elementOrEmpty(element) + "\"";
    }).join(separator);
  }).join('\n');
};

**Comment by tnehme** [comment]
Still returning 
return "\"" + elementOrEmpty(element) + "\"";

**Comment by angelo24782** [comment]
Hi guys, enclosingCharacter doesn't always work. I have set it to an empty string and sometimes it just jumps back to the default double quote. Can somebody look into this?

**Comment by anooj-shah** [comment]
Yes, I am having the same issue @angelo24782

**Comment by jaymjax1** [comment]
Hi, is this issue still open!

**Comment by DannyDevil0** [comment]
Same issue, not working....

**Comment by patchcad** [comment]
I'm having the same issue I'm afraid. On my system it works correctly, but when running on the client's machine, the quotation marks get added.

**Comment by VadimCiv** [comment]
Anyone have solution? PLease write here

**Comment by paracino** [comment]
Same issue, when set to empty string it still adds the double quotes...

**Comment by Mokshi-dev** [comment]
By default it was wrapping my data with double quotes like this `""Leo""` but after setting `enclosingCharacter={``}` solved my issue. Now it looks like this `"Leo"`

**Comment by Cleysond10** [comment]
I solved it by changing my lib version to `2.1.9` and using props enclosingCharacter with empty string value, like:

`enclosingCharacter=""`
