### ISSUE TITLE
First fetch data from server then download csv data with same click

### ISSUE THREAD

**Issue by arpitprod** [react-csv/react-csv#72]
First I want to fetch data with API then that data should download with react-csv. 
For this, I want to use single button for both work. 

this time, I'm using like this - 
`<Button onClick={this.fetchData}>Fetch Data</Button>`

```
fetchData() {
  axios.get('api_link')
    .then(({data}) => {
      this.setState({data})
    })
}
```
and then Download data - 

```
<CSVLink
	data={this.state.data}
	headers={this.state.headers}
	filename='AllContent.csv'
	target='_self'
>
	Download me
</CSVLink>
```

but Buttons will show 2 times. it's not good looking for users. 

So, How can I fetch and download data with only one click ?

**Comment by christianallred** [comment]
This is already doable via CSVDownload element. 

https://github.com/abdennour/react-csv#2-csvdownload-component

```
    <div>
        <Button onClick={this.fetchData}>Button</Button>
        {this.state.data != null ? <CSVDownload data={this.state.data} /> : null }
    </div>
```

**Comment by divyabiyani** [comment]
@christianallred Doesn't this solution also will require user to click 2 buttons to download a single csv?

@arpitprod: Hey, I am also working on a similar issue. Did you come  across a solution for this?

**Comment by mriccid** [comment]
@christianallred the problem with that solution is that it will potentially download the CSV every time a render occurs after fetching data. 

I don't think that this component should be responsible for fetching data, so the solution to this problem needs to exist outside of this library. 

Assuming that this component exists on a page that has to fetch some data before, you could try something like this:
- Fetch the data required for the page to render
- Fetch the data for the CSV, but don't let it prevent the rest of the page from loading
- Render the page, but display a loader in place of the CSV download button
- When the data for the CSV has returned, render the CSV button properly

This pattern may help you with this solution: https://lucasmreis.github.io/blog/simple-react-patterns/

**Comment by divyabiyani** [comment]
@mriccid I might be wrong. But, cant we use componentsWillReceiveProps and setState to false again. 

And again when the user clicks the button the state will change and hence, the csv will be downloaded.

I am currently working in a scenario where I have multiple csv download buttons and all of them will fetch huge data and hence, I wont be able to fetch them on render.

**Comment by davecat** [comment]
It should be written like this：
`{ this.state.boolean?<CSVDownload target="_parent" data={data}></CSVDownload>:''}`
`onClick=(){
       this.setState({
            boolean: true
       },() =>{ 
           this.setState({
               boolean: false
           })
       })
}`

**Comment by dixitk13** [comment]
this is what I tried and it works for me: (I use React+Redux)
P.S: This is what @christianallred suggests in the initial comment as well, using react state. 

Made a stateless component like this: 
```
const CSVButton = ({ data, fetchCSVData, fileName }) => {
  
  if (_.isEmpty(data)) {
    return (
      <span onClick={fetchCSVData} className="csv-download">
        CSV <Icon icon="download" />
      </span>
    )
  } else {
    return (
      <CSVDownload
        className="csv-download"
        target="_self"
        filename={fileName}
        data={data}
      />
    )
  }
}
```

the <b>fetchCSVData</b> action, fetches the data in async mode, and dispatches two actions. one for setting the data field and other which un-sets/resets the data field. 

What really happens is, the state change triggers the reload of the stateless component and <b>CSVDownload</b> is rendered in the DOM to initiate the download functionality. The state is reset then to remove the specific element out of the DOM

**Comment by stevehanson** [comment]
The downside of using the `CSVDownload` component is that it doesn't accept the `filename` prop. I ended up getting this to work by setting up a regular button, which, when clicked, fetches the data and then triggers a click of a hidden `CSVLink`:

```js
class MyCsvLink extends React.Component {
  csvLink = React.createRef()
  state = { data: [] }

  fetchData = () => {
    fetch('/mydata').then(data => {
      this.setState({ data }, () => {
        // click the CSVLink component to trigger the CSV download
        this.csvLink.current.link.click()
      })
    })
  }

  render() {
    return (
      <div>
        <button onClick={this.fetchData}>Download CSV</button>

        <CSVLink
          data={this.state.data}
          filename="data.csv"
          className="hidden"
          ref={this.csvLink}
          target="_blank" 
       />
    </div>
    )
  }
}
```

It'd be nice if this plugin exposed a JS API that could be used to trigger a download instead of requiring the `CSVDownload` or `CSVLink` components to be used.

**Comment by vikapath** [comment]
is <CSVLink> working on firefox as well ?  i am having some issues with that.

**Comment by mccabemj** [comment]
A couple of great solutions to the question here. Hopefully @arpitprod they answer your question, please re-open if not. @vikapath please open a new issue if your still having issues with Firefox

**Comment by Beatrice084** [comment]
This worked for me:
<CSVLink data={["Test", 1], ['Test', 2]].toString()} filename={this.props.title}><Button>Download CSV</Button></CSVLink>

**Comment by CallumHemsley** [comment]
@stevehanson I'm trying your approach, however when I go to open the csv e.g in excel, the index.html HTML is just shown..

**Comment by iassainov** [comment]
In case anyone is having only a `Ôªø` symbol in CSV, put your `this.csvLink.current.link.click()` inside of the `setTimeout` statement like so:
```
setTimeout(() => {
   this.csvLink.current.link.click();
});
```

**Comment by git-angelo** [comment]
> 
> 
> In case anyone is having only a `Ôªø` symbol in CSV, put your `this.csvLink.current.link.click()` inside of the `setTimeout` statement like so:
> 
> ```
> setTimeout(() => {
>    this.csvLink.current.link.click();
> });
> ```

I confirm, my code was based on this answer: https://stackoverflow.com/a/53558566 and I needed to add a setTimeout to make it work. I did not find a better solution... :(

**Comment by anshuporwal01** [comment]
Follow the given Point -
Define 
1. **const ref = React.useRef(null)**
   const [exportData, setExportData] = useState([])
2.
const onClickExport = async () => {
    showLoadingModal()
    let data = await api.index(userId)
    setExportData(data)
    hideLoadingModal()
    **ref.current.click()**
  }
3.
  <>
        <UiButton
          color="link"
          icon="download"
          size="small"
          onClick={onClickExport}
        />
  </>
4.

<CSVLink data={exportData} filename={fileName}>
  <span ref={ref}></span>
</CSVLink>

**Comment by abdennour** [comment]
Check [README.md](https://github.com/react-csv/react-csv/blob/master/README.md), and specifically the section `🔬 Async + data function`. Enjoy!
Available since react-csv@2.1.8

**Comment by garedean** [comment]
@abdennour I've tried following the 'Async + data function' approach using react-csv version 2.2.2, copying the example closely (but using my own async function/request), and reliably get the following error:

```
dev-1214.js:1 Uncaught TypeError: Data should be a "String", "Array of arrays" OR "Array of objects" 
    at toCSV (core.js:1:3429)
    at buildURI (core.js:1:3625)
    at CSVLink.buildURI (Link.js:1:2399)
    at CSVLink.render (Link.js:1:4230)
    at finishClassComponent (one-vui-9e10834c-dev.js:1:566704)
    at updateClassComponent (one-vui-9e10834c-dev.js:1:566126)
    at beginWork (one-vui-9e10834c-dev.js:1:584296)
    at HTMLUnknownElement.callCallback (one-vui-9e10834c-dev.js:1:422607)
    at HTMLUnknownElement.nrWrapper (dev-1214.js:1:30034)
    at Object.invokeGuardedCallbackDev (one-vui-9e10834c-dev.js:1:422975)
```

A stripped-down version of my implementation:

```
export default class DownloadUsers extends Component {
  constructor(props) {
    super(props);

    this.state = {
      listOfUsers: [],
    };
  }

  fetchData = (event, done) => {
    Querier.query({
      query: someQuery
    }).then(({ data }) => {
      const users = data.listOfUsers;
      this.setState({ listOfUsers });
      done(true);
    });
  };

  dataFromListOfUsersState = () => {
    return this.state.listOfUsers;
  };

  render() {
    return (
      <CSVLink data={this.dataFromListOfUsersState} asyncOnClick={true} onClick={this.fetchData}>
        Download CSV
      </CSVLink>
    );
  }
}
```

Any ideas before I file an issue? And thank you for your work on this excellent package.

**Comment by kundan621** [comment]
> 
@abdennour
I am also facing the same issues. Example code itself is not working and breaking screen by throwing Data should be a "String", "Array of arrays" OR "Array of objects" 

@garedean Did you find any solution?

**Comment by garedean** [comment]
@kundan621 I haven't found a solution to this particular issue however there is a workaround to handle async data loading following the approach described [here](https://www.cluemediator.com/loading-data-asynchronously-and-download-csv-using-react-csv) or [here](https://github.com/react-csv/react-csv/issues/189#issue-525778778).

**Comment by kundan621** [comment]
> @kundan621 I haven't found a solution to this particular issue however there is a workaround to handle async data loading following the approach described [here](https://www.cluemediator.com/loading-data-asynchronously-and-download-csv-using-react-csv) or [here](https://github.com/react-csv/react-csv/issues/189#issue-525778778).

Thank you @garedean :)

**Comment by rsxdalv** [comment]
Given that the function for _data_ property does not appear to actually work, I suggest removing it from the docs.
