### ISSUE TITLE
CSV output has unwanted characters in the result.

### ISSUE THREAD

**Issue by dpramani** [react-csv/react-csv#89]
My first field in the CSV file is id but it comes as ï»¿"id" in that field only.  Can anyone please help in this issue. I will share a screenshot of the resultant CSV file.  

Thanks
<img width="1271" alt="screen shot 2018-07-20 at 11 45 28 am" src="https://user-images.githubusercontent.com/26373096/43017904-111cd594-8c15-11e8-9918-384efe2b91e7.png">

**Comment by hindmanj** [comment]
Looks like a BOM was added.  You should specify you do not want the BOM.

**Comment by dpramani** [comment]
Thanks @hindmanj . The issue is solved now. I used the react-csv-2 package. The bug is removed there.

**Comment by mriccid** [comment]
@seonixx you can set the `uFEFF` prop to true on your component, e.g. `<CSVLink uFEFF={false} ... />`

**Comment by mccabemj** [comment]
I am closing this issue as it was fixed in #38 as per @mriccid comment
